[package]
name = "UraWebFramework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower = "0.4.13"
tower-service = "0.3.2"
hyper = "1.2.0"
tokio = "1.36.0"
tokio-stream = "0.1.14"
